### ISSUE TITLE
urllib issue

### ISSUE THREAD

**Issue by pbzeppelin** [boramalper/himawaripy#20] opened 2016-02-05 01:24 UTC
Firstly, I had to manually set the DE string to "mate" as it fails to detect the DE in Arch for some reason. 

Anyways, I get the following error output:

[tv@Urban-HTPC himawaripy]$ ./himawaripy.py
Updating...
Latest version: 2016/02/05/00:50:00 GMT

Downloading tiles: 64/64 completed
Downloaded

Error while parsing options: Unknown option -type.
Run 'gconftool-2 --help' to see a full list of available command line options.
Done!

**Comment by boramalper** [comment] 2016-02-05 11:41
It should work now. Can you please check again and write the result?

**Comment by ghost** [comment] 2016-02-05 11:58
@pbzeppelin I do update the AUR package this evening (in approx 6H) : https://aur.archlinux.org/packages/himawaripy-git/

**Comment by ghost** [comment] 2016-02-05 18:24
Package updated with latests commit and merge to master

**Comment by boramalper** [comment] 2016-02-05 18:29
Thank you! :)

**Comment by ghost** [comment] 2016-02-05 18:32
You're welcome, don't forget to close the issue if this is ok for you.
And this conversation could interested you : https://www.reddit.com/r/linux/comments/445gil/i_wrote_a_python_script_that_puts_a_nearrealtime/czoxymk

**Comment by boramalper** [comment] 2016-02-05 19:29
I'm waiting for an acknowledgement from @pbzeppelin to close it.

**Comment by pbzeppelin** [comment] 2016-02-05 19:36
I won't be home until this evening, but I'll try it then. Also, I'll use the AUR package, that way I can update it easier.

**Comment by pbzeppelin** [comment] 2016-02-06 01:48
Installed the package from the AUR.

Now, I get the following error when running it:

himawaripy
Updating...
Latest version: 2016/02/06 01:20:00 GMT

multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/lib/python3.5/urllib/request.py", line 1240, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python3.5/http/client.py", line 1083, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1128, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1079, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 911, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 854, in send
    self.connect()
  File "/usr/lib/python3.5/http/client.py", line 826, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.5/socket.py", line 693, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.5/socket.py", line 732, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(_args, *_kwds))
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 44, in mapstar
    return list(map(_args))
  File "/usr/lib/python3.5/site-packages/himawaripy/himawaripy.py", line 38, in download_chunk
    with urlopen(url_format.format(level, width, strftime("%Y/%m/%d/%H%M%S", latest), x, y)) as tile_w:
  File "/usr/lib/python3.5/urllib/request.py", line 162, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 465, in open
    response = self._open(req, data)
  File "/usr/lib/python3.5/urllib/request.py", line 483, in _open
    '_open', req)
  File "/usr/lib/python3.5/urllib/request.py", line 443, in _call_chain
    result = func(_args)
  File "/usr/lib/python3.5/urllib/request.py", line 1268, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.5/urllib/request.py", line 1242, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -2] Name or service not known>
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/bin/himawaripy", line 5, in <module>
    main()
  File "/usr/lib/python3.5/site-packages/himawaripy/himawaripy.py", line 63, in main
    res = p.map(download_chunk, product(range(level), range(level), (latest,)))
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 260, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 608, in get
    raise self._value
urllib.error.URLError: <urlopen error [Errno -2] Name or service not known>

**Comment by rbong** [comment] 2016-02-06 03:49
> Firstly, I had to manually set the DE string to "mate" as it fails to detect the DE in Arch for some reason.

I also had this problem. Add "mate" to line 55 in utils.py.

```
    if current_desktop in ["gnome", "unity", "kde", "gnome-classic", "mate"]:
```

Since you installed this with the package manager, it should be in /usr/lib/python3.5/site-packages himawaripy.

I was not able to replicate the http error. Ensure that you have the newest version of python3-urllib.

**Comment by ghost** [comment] 2016-02-06 08:25
Mate is already in the last package I build in AUR.
@pbzeppelin Can you install this package an try again ?
    python-urllib3

If this works, I'll add the dependency in the package.

**Comment by pbzeppelin** [comment] 2016-02-06 17:29
- re-installed python-urllib3 (@rbong: no such thing as python3-urllib)
- re-installed himawaripy-git

No change.

Also, @rbong: I added mate to that array, and that got rid of that error. Thanks; that's better than hardcoding it to always detect MATE...Thankfully XFCE doesn't like the HTPC setup. (Won't re-init the display after it's been unplugged/turned off)

**Comment by boramalper** [comment] 2016-02-06 17:33
@rbong @pbzeppelin But isn't mate already in the list (or array)? You shouldn't need to add it, should you?

**Comment by pbzeppelin** [comment] 2016-02-06 17:57
Considering I just added it like 35 minutes ago, I'm gonna go with no. But, that's the AUR PKG..It may need to be updated, assuming the patch to add it was merged. (it looks like it was)

**Comment by rbong** [comment] 2016-02-06 17:59
MATE was in the other array. With the pull request merged, it's now in both.

@pbzeppelin: excuse me, I meant python-urllib3

**Comment by boramalper** [comment] 2016-02-06 18:01
Fine then. Closing the issue.

Many thanks to everyone! :)

**Comment by rbong** [comment] 2016-02-06 18:09
I think that only fixed MATE detection, not the url error.

**Comment by ghost** [comment] 2016-02-06 18:11
I think you should open a new issue if you have an other ... issue :)

**Comment by pbzeppelin** [comment] 2016-02-06 19:08
Excuse me, that did not fix _this_ issue, this ticket should not be closed yet.

edit: by this issue, I mean the urllib error.

**Comment by boramalper** [comment] 2016-02-06 20:31
Let's see if we can find a solution...

I think the problem is about name resolution, can you please try this command:

```
nc himawari8.nict.go.jp 80
```

Wait for a 20 seconds. If it prints `nc: getaddrinfo: Name or service not known`, then it means that your machine can not resolve the domain name. If it doesn't print anything, well, we'll try to figure it out. :)

**Comment by pbzeppelin** [comment] 2016-02-07 01:19
>[tv@HTPC ~]$ nc himawari8.nict.go.jp 80
>-bash: nc: command not found


Hmmmm.. Did I type that right?

For what it's worth, I can ping that address without a response. It can definitely resolve the address to 133.243.243.104.

**Comment by pbzeppelin** [comment] 2016-02-07 03:01
Okay, I had to install the gnu-netcat package, and ran the command...and it printed nothing.

**Comment by ghost** [comment] 2016-02-07 09:27
Reinstall the AUR package, and don't change anything from the script (don't change options).
And then I would try that :

```
curl http://himawari8-dl.nict.go.jp/himawari8/img/D531106/latest.json
```

It should print something like :

```
{"date":"2016-02-07 09:00:00","file":"PI_H08_20160207_0900_TRC_FLDK_R10_PGPFD.png"}
```
- Do you have a proxy ?

**Comment by pbzeppelin** [comment] 2016-02-07 19:04
- No proxy

---

Curl worked. It responded with:

> curl http://himawari8-dl.nict.go.jp/himawari8/img/D531106/latest.json
> {"date":"2016-02-07 18:40:00","file":"PI_H08_20160207_1840_TRC_FLDK_R10_PGPFD.png"}

**Comment by pbzeppelin** [comment] 2016-02-07 19:07
Also, reinstalling changed nothing; still getting the same error. You'll also want to mention that setuptools is required...

**Comment by AbuMaia** [comment] 2016-07-26 23:37
I am having this urllib issue as well, on Ubuntu 16.04 running Gnome Shell 3.18.5.

```
abumaia@AbuMaia:~/Downloads/himawaripy-master$ himawaripy
Updating...
Latest version: 2016/07/26 23:10:00 GMT
Offset version: 2016/07/26 07:10:00 GMT

Downloading tiles: 4/16 completedmultiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.5/urllib/request.py", line 1254, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1151, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/lib/python3.5/http/client.py", line 849, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.5/socket.py", line 693, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.5/socket.py", line 732, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/usr/local/lib/python3.5/dist-packages/himawaripy-1.1-py3.5.egg/himawaripy/himawaripy.py", line 53, in download_chunk
    with urlopen(url_format.format(level, width, strftime("%Y/%m/%d/%H%M%S", latest), x, y)) as tile_w:
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 466, in open
    response = self._open(req, data)
  File "/usr/lib/python3.5/urllib/request.py", line 484, in _open
    '_open', req)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 1282, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.5/urllib/request.py", line 1256, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -3] Temporary failure in name resolution>
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/himawaripy", line 9, in <module>
    load_entry_point('himawaripy==1.1', 'console_scripts', 'himawaripy')()
  File "/usr/local/lib/python3.5/dist-packages/himawaripy-1.1-py3.5.egg/himawaripy/himawaripy.py", line 88, in main
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 260, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 608, in get
    raise self._value
urllib.error.URLError: <urlopen error [Errno -3] Temporary failure in name resolution>
```

I have tried the

```
nc himawari8.nict.go.jp 80
```

code, but it just sits there, and eventually comes back to the prompt with no response.

Curl worked:

```
abumaia@AbuMaia:~/Downloads/himawaripy-master$ curl http://himawari8-dl.nict.go.jp/himawari8/img/D531106/latest.json
{"date":"2016-07-26 23:50:00","file":"PI_H08_20160726_2350_TRC_FLDK_R10_PGPFD.png"}
```

**Comment by boramalper** [comment] 2016-08-03 07:30
@AbuMaia Well, it says `Temporary failure in name resolution` so let's hope that it was a temporary issue. :)

Can you check if it recurs?

**Comment by AbuMaia** [comment] 2016-08-03 12:24
Same error.

**Comment by boramalper** [comment] 2016-08-03 13:47
@AbuMaia I don't know the solution yet, but can you please open up another issue?

**Comment by mrugna** [comment] 2016-08-04 15:06
Same issue here. If I run it independently it works fine, but every time on crontab it fails the same way

**Comment by boramalper** [comment] 2019-04-24 21:47
Closing the issue due to inactivity, feel free to open a new issue if the problem persists.

**Closed as completed by boramalper** 2019-04-24 21:47 UTC
